Error: Return an empty array or collection instead of null
Reason: operation with null can cause null pointer exception so to avoid null pointer exception empty array or collections are returned.